---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  become_user: root
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Instal tools for clickhouse
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - dirmngr
    - name: Install key
      shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
    - name: Instal deb package
      shell: echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install clickhouse
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - clickhouse-server
        - clickhouse-client
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: Instal Vector
  hosts: vector
  become: true
  become_user: root
  handlers: 
    - name: Restart Vector
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get bash for add vector deb
      get_url:
        url: "https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh"
        dest: "/home/ubuntu/vector.sh"
    - name: Add package vector
      shell: bash /home/ubuntu/vector.sh
    - name: Install vector
      apt:
        name: vector
        state: present
    - name: Configuration vector
      template:
        src: /home/cfdata/ansible_module/hw_3_yandex/playbook/template/vector.j2
        dest: /home/ubuntu/vector.sh
      notify: Restart Vector

- name: Install Lighthouse and NGINX
  hosts: lighthouse
  become: true
  become_user: root
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
  tasks:
    - name: Installing git
      apt:
        name: git
        state: present
    - name: Clone git Lighthouse
      git:
        repo: https://github.com/VKCOM/lighthouse.git
        dest: /home/ubuntu/lighthouse
        single_branch: yes
        version: master
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Delete default config Nginx
      file:
        path: /etc/nginx/nginx.conf
        state: absent
    - name: Config Nginx for Lighthouse
      template:
        src: /home/cfdata/ansible_module/hw_3_yandex/playbook/template/nginx.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx