---
- name: Install Clickhouse # Play для установки clickhouse
  hosts: clickhouse # Вводим имя хоста на который будетустанавливаться ПО
  become: true # Уставнавливаем переменную для использования sudo
  become_user: root # Устанвливаем пользователя подкотрым будет устанавливаться ПО 
  handlers: # Handler который рестартует сервис clickhouse-server после установки
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks: 
    - name: Install Clickhouse
      hosts: clickhouse
      roles:
        - clickhouse
- name: Instal Vector # Play для установки Vector
      hosts: vector
      become: true
      become_user: root
      handlers:  # Handler который рестартует сервис vector после настройки
        - name: Restart Vector
          ansible.builtin.service:
          name: vector
            state: restarted
  tasks:
    - name: Get bash for add vector deb # Скачивает bash скрипт для установки пакета Vector
      get_url:
        url: "https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh"
        dest: "/home/ubuntu/vector.sh"
    - name: Add package vector # Добавление пакета Vector
      shell: bash /home/ubuntu/vector.sh
    - name: Install vector # Установка Vector
      apt:
        name: vector
        state: present
    - name: Configuration vector # Базовая настройка Vector с помощью шаблона jinja2 
      template:
        src: /home/cfdata/ansible_module/hw_3_yandex/playbook/template/vector.j2
        dest: /home/ubuntu/vector.sh
      notify: Restart Vector # Вызоыв handler

- name: Install Lighthouse and NGINX # Play для установки NGNIX и Lighthouse
  hosts: lighthouse
  become: true
  become_user: root
  handlers: # Handler который рестартует сервис NGINX после настройки
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
  tasks:
    - name: Installing git # Устанавливаем git
      apt:
        name: git
        state: present
    - name: Clone git Lighthouse # Клонируем репозиторий Lighthouse
      git:
        repo: https://github.com/VKCOM/lighthouse.git
        dest: /home/ubuntu/lighthouse
        single_branch: yes
        version: master
    - name: Install nginx # Устанавливаем NGINX
      apt:
        name: nginx
        state: present
    - name: Delete default config Nginx # Удаляем default config nginx
      file:
        path: /etc/nginx/nginx.conf
        state: absent
    - name: Config Nginx for Lighthouse # Создаем новый конфиг для nginx по шаблону nginx.j2
      template:
        src: /home/cfdata/ansible_module/hw_3_yandex/playbook/template/nginx.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx # вызов handler